export default {
    install(Vue) {
        window.facebookAccessToken = 'EAAKgXuhD0hABACmD7m1QuXOpVlvD3UgaZCD6PCBxZAZClPQlKBPir9fHgmCQP5W16fOMU8CkzhjxCrFI80iF8KVLX8ziSEjMF0uJNfWZCjLgiIqZCmawtjiRWzSrO7258ZBuIB9FZBXfWGvLnbWpMwfsyxppbbZCUEZC0X4opbp8COfLkaX0IZCAIr1WfFejRPwZBUZD'
        window.facebookPixelId = '740173934391972'
        window.facebookTestEventCode = 'TEST6553'

        require('js-helper-methods');
        require('helper-vue-components').default.install(Vue);
        require('description-vue-components').default.install(Vue);
        require('text-contents-vue-components').default.install(Vue);
        require('./RequestOfferForm/register.js').default.install(Vue);
        require('./Templates/templateRegister.js').default.install();

        registerVueComponent(
            'dynamic-web-navigation-bar',
            require('./NavigationBar/NavigationBar/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/NavigationBar/NavigationBar/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-navigation-link',
            require('./NavigationBar/Links/NavigationLink/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/NavigationBar/Links/NavigationLink/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-button-navigation-link',
            require('./NavigationBar/Links/ButtonNavigationLink/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/NavigationBar/Links/ButtonNavigationLink/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-dropdown-navigation-link',
            require('./NavigationBar/Links/DropdownNavigationLink/NavigationLink/Component.vue')
                .default,
            Vue,
            'dynamic-web-vue-components/NavigationBar/Links/DropdownNavigationLink/NavigationLink/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-list-dropdown',
            require('./NavigationBar/Links/DropdownNavigationLink/Dropdowns/ListDropdown/Component.vue')
                .default,
            Vue,
            'dynamic-web-vue-components/NavigationBar/Links/DropdownNavigationLink/Dropdowns/ListDropdown/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-link-dropdown-item',
            require('./NavigationBar/Links/DropdownNavigationLink/Dropdowns/LinkItem/Component.vue')
                .default,
            Vue,
            'dynamic-web-vue-components/NavigationBar/Links/DropdownNavigationLink/Dropdowns/LinkItem/Component.vue'
        );

        registerVueComponent(
            'dynamic-web-header',
            require('./Header/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/Header/Component.vue'
        );

        registerVueComponent(
            'dynamic-web-offer',
            require('./Offer/Offer/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/Offer/Offer/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-offer-container',
            require('./Offer/Container/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/Offer/Container/Component.vue'
        );

        registerVueComponent(
            'dynamic-web-services',
            require('./Services/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/Services/Component.vue'
        );

        registerVueComponent(
            'dynamic-web-request-offer-form',
            require('./RequestOfferForm/Form/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/RequestOfferForm/Form/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-success-session-message',
            require('./SessionMessages/SuccessMessage/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/SessionMessages/SuccessMessage/Component.vue'
        );

        registerVueComponent(
            'dynamic-web-footer',
            require('./Footer/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/Footer/Component.vue'
        );

        registerVueComponent(
            'dynamic-web-upper-line-text-content',
            require('./TextContents/TextContentWithUpperLine/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/TextContentWithUpperLine/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-middle-line-text-content',
            require('./TextContents/TextContentWithMiddleLine/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/TextContentWithMiddleLine/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-medium-text-content',
            require('./TextContents/MediumTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/MediumTextContent/Component.vue'
        );
        registerVueComponent(
          'dynamic-web-medium-text-content-with-button',
          require('./TextContents/MediumTextContentWithButton/Component.vue')
            .default,
          Vue,
          'dynamic-web-vue-components/TextContents/MediumTextContentWithButton/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-team-medium-text-content',
            require('./TextContents/TeamMediumTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/TeamMediumTextContent/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-white-medium-text-content',
            require('./TextContents/WhiteMediumTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/WhiteMediumTextContent/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-text-content-with-icon',
            require('./TextContents/TextContentWithIcon/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/TextContentWithIcon/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-small-text-content',
            require('./TextContents/SmallTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/SmallTextContent/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-request-offer-small-text-content',
            require('./TextContents/RequestOfferSmallTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/RequestOfferSmallTextContent/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-articles-small-text-content',
            require('./TextContents/ArticlesSmallTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/TextContents/ArticlesSmallTextContent/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-dark-link',
            require('./DarkLink/Component.vue').default,
            Vue,
            'dynamic-web-vue-componentsDarkLink/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-button-icon-link',
            require('./ButtonIconLink/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/ButtonIconLink/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-description-section',
            require('./Description/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/Description/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-team',
            require('./Team/Team/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/Team/Team/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-team-member',
            require('./Team/Member/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/Team/Member/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-how-we-do',
            require('./HowWeDo/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/HowWeDo/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-timeline',
            require('./Timeline/Timeline/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/Timeline/Timeline/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-timeline-item',
            require('./Timeline/TimelineItem/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/Timeline/TimelineItem/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-two-title-text-content',
            require('./TextContents/TwoTitleTextContent/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/TextContents/TwoTitleTextContent/Component.vue'
        );
        registerVueComponent(
            'dynamic-web-latest-works',
            require('./LatestWorks/Component.vue').default,
            Vue,
            'dynamic-web-vue-components/src/LatestWorks/Component.vue'
        );
    },
};
